### ISSUE TITLE
Clarify need to place locks in /tmp

### ISSUE THREAD

**Issue by vemv** [sheerun/filelock#10]
Hi!

The examples in the readme go like this:

```ruby
Filelock '/tmp/path/to/lock' do
  # do blocking operation
end
```

It calls my attention that the lock file is placed at /tmp. Is this the adviced directory to place our file locks?

I'd be more inclined to store them in `Rails.root` or in `Rails.root.join('tmp')`, because:

* that way, these files are more prominently visible
* /tmp sounds like it can be swiped by the OS at any time?

Note that I'm not experiencied with filelocks, so I'm not biased towards any specific approach. Just asking!

Cheers - Victor

**Comment by sheerun** [comment]
It's not a recommendation of any kind, just an example. Do as you please :)

**Comment by vemv** [comment]
But it's an example that makes one hesitate!

Would you change it to `Rails.root.join('tmp', 'example_lock')`?

Else nevermind, question addressed anyway. Thanks!
