### ISSUE TITLE
FAQ: what happens when killing a process holding a lock?

### ISSUE THREAD

**Issue by vemv** [sheerun/filelock#11]
Hey there again,

I could see in the test suite (and checked myself in my server) that when a ruby process holding a lock gets killed, then a new process can grab the lock with no issue. Great!

This concern is probably a FAQ. Would you add this question...

> What happens if my ruby process gets killed while holding a lock? Can new processes acquire this lock?

...and answer accurately? It's awesome that it works as expected, but it would be great to know why (the OS is smart? your ruby implementation is smart?).

Cheers - Victor

**Comment by sheerun** [comment]
Even if it's SIGKILL?

**Comment by vemv** [comment]
Yes, I tried this with `kill -9` and two ssh sessions to my server.

**Comment by sheerun** [comment]
Hmm. Indeed, there's even a test for it, I forgot :) https://github.com/sheerun/filelock/blob/master/spec/filelock_spec.rb#L220

Maybe you'd like to send a PR? With additional entry in FAQ?

**Comment by vemv** [comment]
Yes I saw the test! :)

As mentioned, I'd want a reasonably detailed reply to the question, which I don't know. Knowing the reason why this works correctly would increase my confidence into this gem.

**Comment by sheerun** [comment]
Added short faq answer
